package br.com.soaexpert.creditoservice;

import javax.jws.WebService;
import javax.xml.ws.BindingType;
import br.com.soaexpert.domain.Credito;
import br.com.soaexpert.domain.Empresa;

/**
 * This class was generated by the JAX-WS RI. Oracle JAX-WS 2.1.5 Generated
 * source version: 2.1
 * 
 */
@WebService(portName = "CreditoServiceSOAP", serviceName = "CreditoService", targetNamespace = "http://soaexpert.com.br/CreditoService/", wsdlLocation = "/wsdls/CreditoService.wsdl", endpointInterface = "br.com.soaexpert.creditoservice.CreditoService")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class CreditoService_CreditoServiceSOAPImpl implements CreditoService {
	
	public static final String EMPRESA_NOME = "SOA|EXPERT";
	

	public CreditoService_CreditoServiceSOAPImpl() {
	}

	/**
	 * 
	 * @param empresa
	 * @return returns br.com.soaexpert.domain.Credito
	 */
	public Credito verificaCreditoSerasa(Empresa empresa) {
		
		Credito credito = new Credito();
		credito.setSerasa(empresa.getRazaoSocial().equals(EMPRESA_NOME));
		credito.setEmpresa(empresa);
		
		return credito;
	}

	/**
	 * 
	 * @param empresa
	 * @return returns br.com.soaexpert.domain.Credito
	 */
	public Credito verificaCreditoSPC(Empresa empresa) {
		Credito credito = new Credito();
		credito.setSpc(empresa.getRazaoSocial().equals(EMPRESA_NOME));
		credito.setEmpresa(empresa);
		
		return credito;
	}

	/**
	 * 
	 * @param empresa
	 * @return returns br.com.soaexpert.domain.Credito
	 */
	public Credito verificaCreditoCasasBahia(Empresa empresa) {
		Credito credito = new Credito();
		credito.setCasasBahia(empresa.getRazaoSocial().equals(EMPRESA_NOME));
		credito.setEmpresa(empresa);
		
		return credito;
	}

}
